DeleteStockBody:
  allOf:
    - type: object
      properties:
        id:
          $ref: 'stock-entities.schemas.openapi.yaml#/StockId'
        lock:
          $ref: 'stock-entities.schemas.openapi.yaml#/StockLock'