StockType:
  type: string
  enum:
    - SHARE
    - BOND

StockId:
  type: object
  properties:
    value:
      type: string
      format: uuid

StockPermission:
  type: string
  enum:
    - find
    - update
    - delete

StockLock:
  type: string
  description: Optimistic lock version

BaseStock:
  type: object
  description: Base object for create and update ops
  properties:
    name:
      type: string
    type:
      $ref: '#/StockType'

StockResponseBody:
  allOf:
    - $ref: '#/BaseStock'
    - type: object
      properties:
        id:
          $ref: '#/StockId'
        userId:
          $ref: '../infrastructure.schemas.openapi.yaml#/UserId'
        lock:
          $ref: '#/StockLock'
        permissions:
          type: array
          uniqueItems: true
          items:
            $ref: '#/StockPermission'

StockResponseSingle:
  allOf:
    - type: object
      description: Response with single item
      properties:
        stock:
          $ref: '#/StockResponseBody'

StockResponseMultiple:
  allOf:
    - type: object
      description: Response with multiple item
      properties:
        stocks:
          type: array
          items:
            $ref: '#/StockResponseBody'