[versions]
kotlin-version = "1.9.22"
coroutines-version = "1.8.0"
okhttp-version = "4.12.0"
jackson-version = "2.16.1"
kotlix-datetime-version = "0.5.0"
binary-compability-validator = "0.13.2"
owasp-version = "8.0.0"

jvm-compiler = "11"
jvm-language = "17"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-version" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-version" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }
jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlix-datetime-version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
binary-compatibility-validator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "binary-compability-validator" }
owasp = { module = "org.owasp:dependency-check-gradle", version.ref = "owasp-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-version" }
