version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./volumes/liquibase:/liquibase/changelog
    depends_on:
      cassandra:
        condition: service_healthy
    command: [ "--defaults-file=/liquibase/changelog/liquibase.properties", "--search-path=/liquibase/changelog", "--url=jdbc:cassandra://cassandra:9042/test_keyspace", "update" ]
