name: Gradle Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Generate log models
      run: ./gradlew :project:stocktrack-log:stocktrack-log-model:clean :project:stocktrack-log:stocktrack-log-model:openApiGenerate

    - name: Generate api models
      run: ./gradlew :project:stocktrack-backend:stocktrack-api-v1-model-kotlin:clean :project:stocktrack-backend:stocktrack-api-v1-model-kotlin:openApiGenerate

    - name: Build & Test api mapper module
      run: ./gradlew :project:stocktrack-backend:stocktrack-api-v1-mapper:clean :project:stocktrack-backend:stocktrack-api-v1-mapper:classes :project:stocktrack-backend:stocktrack-api-v1-mapper:test

    - name: Build & Run repository in-memory db tests
      run: ./gradlew :project:stocktrack-backend:stocktrack-repository-in-memory:clean :project:stocktrack-backend:stocktrack-repository-in-memory:classes :project:stocktrack-backend:stocktrack-repository-in-memory:test

    - name: Build & Run repository postgres tests
      run: ./gradlew :project:stocktrack-backend:stocktrack-repository-postgresql:clean :project:stocktrack-backend:stocktrack-repository-postgresql:classes :project:stocktrack-backend:stocktrack-repository-postgresql:test

    - name: Build & Run e2e tests
      run: ./gradlew :project:stocktrack-test:stocktrack-test-e2e:clean :project:stocktrack-test:stocktrack-test-e2e:classes :project:stocktrack-test:stocktrack-test-e2e:test

    - name: Build & Run Ktor integration tests
      run: ./gradlew :project:stocktrack-test:stocktrack-test-integration-ktor:clean :project:stocktrack-test:stocktrack-test-integration-ktor:classes :project:stocktrack-test:stocktrack-test-integration-ktor:test

    - name: Build & Push Ktor docker image
      run: ./gradlew :project:stocktrack-backend:stocktrack-bootstrap-ktor:clean :project:stocktrack-backend:stocktrack-bootstrap-ktor:pushDockerImage -PdockerUsername=${{ secrets.DOCKER_USERNAME }} -PdockerPassword=${{ secrets.DOCKER_PASSWORD }}

